### ISSUE TITLE
HMG

### ISSUE THREAD

**Issue by JonBons** [SignalCommunity/Wavelength#1]
DerRob: HMG dont loadout good.( HMG Is missing a loadout I cant give him a loadout???)
MysticalPony: Something strange is happening with this, this comment is a reminded for me to look into this tomorrow.

**Comment by derbismarck** [comment]
This is simply a matter of not having enough unit classnames in base game to allow us to create each of our attachment teams without having the classnames be completely unrelated to the unit types.
