### ISSUE TITLE
BW Framework Tab

### ISSUE THREAD

**Issue by Winifridal** [SignalCommunity/Wavelength#10]
This isn't urgent nor is it game changing, but it seems weird to still have a tab that says 'BW Framework' in the map. I think we should change this to "SCMF" or "SC Framework".

**Comment by JonBons** [comment]
The admin mod creates that.

**Comment by Winifridal** [comment]
I know but KP told me to put a thing here anyway.

**Comment by derbismarck** [comment]
Not something that can be fixed in the framework.
