### ISSUE TITLE
Loadout Standard

### ISSUE THREAD

**Issue by JonBons** [SignalCommunity/Wavelength#2]
DerRob:
Repair Specialist, Explosive Specialist and Mine Specialist are not independent lifeforms.

Problem : Repair Specialist, Explosive Specialist use crewman helmet , uniform and Repair Specialist vest

Bismarck: 
Loadouts are not maintained. It is up to mission makers to ensure that their loadouts make sense. If someone WANTS to fix all of the default loadouts, feel free, but we never use them so it makes no sense to worry about them. Additionally, "Repair spec", "Explosive spec" and "Mine spec" are not different enough of purposes to warrant having their own classes and definitions.

MysticalPony:
This will be fixed when we move to full 3den when apex comes out. Ace has a way to make non engineer units be able to repair but works most elegantly inside 3eden. This would allow us to separate the heli crew chief engineer from the tank crew driver engineer.

**Comment by derbismarck** [comment]
They aren't and shouldn't be separate things in terms of gear. Open a new issue request for other features or issues that MysticalPony or you may want with these different types of engineers.
