### ISSUE TITLE
Safestart fires indicator

### ISSUE THREAD

**Issue by derbismarck** [SignalCommunity/Wavelength#5]
A message in systemChat or in a hint that notifies everybody when someone is firing and who they are.

**Comment by KillPact** [comment]
Idk about notifying everybody, was thinking of system messages like the admin menu does for the administrators. Example what the bw admin menu does when any action is taken inside of that

**Comment by derbismarck** [comment]
Added with PR #8

**Comment by JonBons** [comment]
Might want to move this to the addon.

**Comment by derbismarck** [comment]
Having it in the framework makes it more easy to apply updates to the addon without worrying about fucking with the code we changed.

**Comment by JonBons** [comment]
I say this gets moved to the addon after its been in use for a while and we don't need to make any more changes.
