### ISSUE TITLE
No unique class names for HAT team

### ISSUE THREAD

**Issue by Slendermang** [SignalCommunity/Wavelength#9]
As it stands right now MAT and HAT use the same class names, 'B_soldier_AT_F' & 'B_Soldier_AAT_F'

**Comment by KillPact** [comment]
Issue is that BI doesn't have any good classnames for the heavy asset teams that allow for assistants. I think I'll go ahead and fix this later unless someone already started on it.

**Comment by derbismarck** [comment]
Fixed with PR #13
